spring.application.name=InterviewCode
server.port = 8080
spring.datasource.username = ms
spring.datasource.password =

spring.datasource.url=jdbc:h2:mem:iniven
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

